defmodule Improve.Repo.Migrations.AddUserTimezone do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :timezone, :text, null: false, default: "Etc/UTC"
    end
  end

  def down do
    alter table(:users) do
      remove :timezone
    end
  end
end
