defmodule Improve.Repo.Migrations.AddAuthoredPlanContent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:schedules, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :owner_type, :text, null: false
      add :owner_id, :uuid, null: false
      add :kind, :text, null: false
      add :rules, :map, null: false, default: %{}
      add :starts_on, :date, null: false
      add :ends_on, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "schedules_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:pools, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "pools_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:pools, [:plan_id, :key], name: "pools_unique_key_per_plan_index")

    create table(:pool_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "pool_memberships_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :pool_id,
          references(:pools,
            column: :id,
            name: "pool_memberships_pool_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :item_id, :uuid, null: false
    end

    create unique_index(:pool_memberships, [:pool_id, :item_id],
             name: "pool_memberships_unique_item_per_pool_index"
           )

    create table(:items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:pool_memberships) do
      modify :item_id,
             references(:items,
               column: :id,
               name: "pool_memberships_item_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:items) do
      add :key, :text, null: false
      add :name, :text, null: false
      add :facts, :map, null: false, default: %{}
      add :stateful, :boolean, null: false, default: false
      add :archived_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "items_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :item_type_id, :uuid, null: false
    end

    create unique_index(:items, [:plan_id, :key], name: "items_unique_key_per_plan_index")

    create table(:item_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:items) do
      modify :item_type_id,
             references(:item_types,
               column: :id,
               name: "items_item_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:item_types) do
      add :key, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :facts_schema, :map, null: false, default: %{}
      add :display_hints, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "item_types_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:item_types, [:plan_id, :key],
             name: "item_types_unique_key_per_plan_index"
           )

    create table(:event_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :payload_schema, :map, null: false, default: %{}
      add :item_link_roles, :map, null: false, default: %{}
      add :effect_rules, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "event_types_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:event_types, [:plan_id, :key],
             name: "event_types_unique_key_per_plan_index"
           )

    create table(:environments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :available_item_ids, {:array, :uuid}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "environments_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:environments, [:plan_id, :key],
             name: "environments_unique_key_per_plan_index"
           )
  end

  def down do
    drop constraint(:environments, "environments_plan_id_fkey")

    drop_if_exists unique_index(:environments, [:plan_id, :key],
                     name: "environments_unique_key_per_plan_index"
                   )

    drop table(:environments)

    drop constraint(:event_types, "event_types_plan_id_fkey")

    drop_if_exists unique_index(:event_types, [:plan_id, :key],
                     name: "event_types_unique_key_per_plan_index"
                   )

    drop table(:event_types)

    drop constraint(:item_types, "item_types_plan_id_fkey")

    drop_if_exists unique_index(:item_types, [:plan_id, :key],
                     name: "item_types_unique_key_per_plan_index"
                   )

    alter table(:item_types) do
      remove :plan_id
      remove :updated_at
      remove :inserted_at
      remove :display_hints
      remove :facts_schema
      remove :description
      remove :name
      remove :key
    end

    drop constraint(:items, "items_item_type_id_fkey")

    alter table(:items) do
      modify :item_type_id, :uuid
    end

    drop table(:item_types)

    drop constraint(:items, "items_plan_id_fkey")

    drop_if_exists unique_index(:items, [:plan_id, :key], name: "items_unique_key_per_plan_index")

    alter table(:items) do
      remove :item_type_id
      remove :plan_id
      remove :updated_at
      remove :inserted_at
      remove :archived_at
      remove :stateful
      remove :facts
      remove :name
      remove :key
    end

    drop constraint(:pool_memberships, "pool_memberships_item_id_fkey")

    alter table(:pool_memberships) do
      modify :item_id, :uuid
    end

    drop table(:items)

    drop constraint(:pool_memberships, "pool_memberships_plan_id_fkey")

    drop constraint(:pool_memberships, "pool_memberships_pool_id_fkey")

    drop_if_exists unique_index(:pool_memberships, [:pool_id, :item_id],
                     name: "pool_memberships_unique_item_per_pool_index"
                   )

    drop table(:pool_memberships)

    drop constraint(:pools, "pools_plan_id_fkey")

    drop_if_exists unique_index(:pools, [:plan_id, :key], name: "pools_unique_key_per_plan_index")

    drop table(:pools)

    drop constraint(:schedules, "schedules_plan_id_fkey")

    drop table(:schedules)
  end
end
