defmodule Improve.Repo.Migrations.AddEventIdempotency do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:event_instances) do
      add :client_event_id, :text
      add :client_operation_id, :text
      add :client_device_id, :text
      add :idempotency_key, :text
    end

    create unique_index(:event_instances, [:plan_id, :client_device_id, :client_operation_id],
             name: "event_instances_unique_client_operation_per_plan_device_index",
             where: "(client_device_id IS NOT NULL AND client_operation_id IS NOT NULL)"
           )

    create unique_index(:event_instances, [:plan_id, :client_device_id, :idempotency_key],
             name: "event_instances_unique_idempotency_key_per_plan_device_index",
             where: "(client_device_id IS NOT NULL AND idempotency_key IS NOT NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:event_instances, [:plan_id, :client_device_id, :idempotency_key],
                     name: "event_instances_unique_idempotency_key_per_plan_device_index"
                   )

    drop_if_exists unique_index(
                     :event_instances,
                     [:plan_id, :client_device_id, :client_operation_id],
                     name: "event_instances_unique_client_operation_per_plan_device_index"
                   )

    alter table(:event_instances) do
      remove :idempotency_key
      remove :client_device_id
      remove :client_operation_id
      remove :client_event_id
    end
  end
end
