defmodule Improve.Repo.Migrations.AddSessionsAndJournal do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:slot_results, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "planned"
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "slot_results_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :session_occurrence_id, :uuid, null: false
      add :session_slot_id, :uuid, null: false
      add :recommended_item_id, :uuid
      add :actual_item_id, :uuid
      add :event_instance_id, :uuid
    end

    create table(:session_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :completion_policy, :map, null: false, default: %{}
      add :missed_policy, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "session_templates_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :environment_id,
          references(:environments,
            column: :id,
            name: "session_templates_environment_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:session_templates, [:plan_id, :key],
             name: "session_templates_unique_key_per_plan_index"
           )

    create table(:session_slots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :name, :text, null: false
      add :count, :bigint, null: false, default: 1
      add :optional, :boolean, null: false, default: false
      add :rules, :map, null: false, default: %{}
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "session_slots_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :session_template_id,
          references(:session_templates,
            column: :id,
            name: "session_slots_session_template_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :pool_id,
          references(:pools,
            column: :id,
            name: "session_slots_pool_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:session_slots, [:session_template_id, :key],
             name: "session_slots_unique_key_per_template_index"
           )

    create table(:session_occurrences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:slot_results) do
      modify :session_occurrence_id,
             references(:session_occurrences,
               column: :id,
               name: "slot_results_session_occurrence_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :session_slot_id,
             references(:session_slots,
               column: :id,
               name: "slot_results_session_slot_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :recommended_item_id,
             references(:items,
               column: :id,
               name: "slot_results_recommended_item_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :actual_item_id,
             references(:items,
               column: :id,
               name: "slot_results_actual_item_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:session_occurrences) do
      add :planned_for, :date, null: false
      add :status, :text, null: false, default: "planned"
      add :recommendation_snapshot, :map, null: false, default: %{}
      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :feedback, :map, null: false, default: %{}
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "session_occurrences_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :session_template_id,
          references(:session_templates,
            column: :id,
            name: "session_occurrences_session_template_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:item_effects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :effect_type, :text, null: false
      add :quantity, :decimal
      add :unit, :text
      add :payload, :map, null: false, default: %{}
      add :status, :text, null: false, default: "active"
      add :voided_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "item_effects_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :item_id,
          references(:items,
            column: :id,
            name: "item_effects_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :event_instance_id, :uuid, null: false
      add :replaces_item_effect_id, :uuid
    end

    create table(:event_item_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "event_item_links_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :event_instance_id, :uuid, null: false
      add :item_id, :uuid, null: false
    end

    create table(:event_instances, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:slot_results) do
      modify :event_instance_id,
             references(:event_instances,
               column: :id,
               name: "slot_results_event_instance_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:item_effects) do
      modify :event_instance_id,
             references(:event_instances,
               column: :id,
               name: "item_effects_event_instance_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :replaces_item_effect_id,
             references(:item_effects,
               column: :id,
               name: "item_effects_replaces_item_effect_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:event_item_links) do
      modify :event_instance_id,
             references(:event_instances,
               column: :id,
               name: "event_item_links_event_instance_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :item_id,
             references(:items,
               column: :id,
               name: "event_item_links_item_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:event_instances) do
      add :effective_at, :utc_datetime_usec, null: false
      add :recorded_at, :utc_datetime_usec, null: false
      add :summary, :text, null: false
      add :quantity, :decimal
      add :unit, :text
      add :payload, :map, null: false, default: %{}
      add :note, :text
      add :status, :text, null: false, default: "active"
      add :origin, :text, null: false, default: "manual"
      add :voided_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "event_instances_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :event_type_id,
          references(:event_types,
            column: :id,
            name: "event_instances_event_type_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :session_occurrence_id,
          references(:session_occurrences,
            column: :id,
            name: "event_instances_session_occurrence_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :slot_result_id,
          references(:slot_results,
            column: :id,
            name: "event_instances_slot_result_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :direct_goal_id, :uuid
      add :replaces_event_instance_id, :uuid
    end

    create table(:direct_goals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:event_instances) do
      modify :direct_goal_id,
             references(:direct_goals,
               column: :id,
               name: "event_instances_direct_goal_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :replaces_event_instance_id,
             references(:event_instances,
               column: :id,
               name: "event_instances_replaces_event_instance_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:direct_goals) do
      add :key, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :target, :map, null: false, default: %{}
      add :completion_policy, :map, null: false, default: %{}
      add :missed_policy, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "direct_goals_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :event_type_id,
          references(:event_types,
            column: :id,
            name: "direct_goals_event_type_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:direct_goals, [:plan_id, :key],
             name: "direct_goals_unique_key_per_plan_index"
           )
  end

  def down do
    drop constraint(:direct_goals, "direct_goals_plan_id_fkey")

    drop constraint(:direct_goals, "direct_goals_event_type_id_fkey")

    drop_if_exists unique_index(:direct_goals, [:plan_id, :key],
                     name: "direct_goals_unique_key_per_plan_index"
                   )

    alter table(:direct_goals) do
      remove :event_type_id
      remove :plan_id
      remove :updated_at
      remove :inserted_at
      remove :missed_policy
      remove :completion_policy
      remove :target
      remove :description
      remove :name
      remove :key
    end

    drop constraint(:event_instances, "event_instances_direct_goal_id_fkey")

    drop constraint(:event_instances, "event_instances_replaces_event_instance_id_fkey")

    alter table(:event_instances) do
      modify :replaces_event_instance_id, :uuid
      modify :direct_goal_id, :uuid
    end

    drop table(:direct_goals)

    drop constraint(:event_instances, "event_instances_plan_id_fkey")

    drop constraint(:event_instances, "event_instances_event_type_id_fkey")

    drop constraint(:event_instances, "event_instances_session_occurrence_id_fkey")

    drop constraint(:event_instances, "event_instances_slot_result_id_fkey")

    alter table(:event_instances) do
      remove :replaces_event_instance_id
      remove :direct_goal_id
      remove :slot_result_id
      remove :session_occurrence_id
      remove :event_type_id
      remove :plan_id
      remove :updated_at
      remove :inserted_at
      remove :voided_at
      remove :origin
      remove :status
      remove :note
      remove :payload
      remove :unit
      remove :quantity
      remove :summary
      remove :recorded_at
      remove :effective_at
    end

    drop constraint(:event_item_links, "event_item_links_event_instance_id_fkey")

    drop constraint(:event_item_links, "event_item_links_item_id_fkey")

    alter table(:event_item_links) do
      modify :item_id, :uuid
      modify :event_instance_id, :uuid
    end

    drop constraint(:item_effects, "item_effects_event_instance_id_fkey")

    drop constraint(:item_effects, "item_effects_replaces_item_effect_id_fkey")

    alter table(:item_effects) do
      modify :replaces_item_effect_id, :uuid
      modify :event_instance_id, :uuid
    end

    drop constraint(:slot_results, "slot_results_event_instance_id_fkey")

    alter table(:slot_results) do
      modify :event_instance_id, :uuid
    end

    drop table(:event_instances)

    drop constraint(:event_item_links, "event_item_links_plan_id_fkey")

    drop table(:event_item_links)

    drop constraint(:item_effects, "item_effects_plan_id_fkey")

    drop constraint(:item_effects, "item_effects_item_id_fkey")

    drop table(:item_effects)

    drop constraint(:session_occurrences, "session_occurrences_plan_id_fkey")

    drop constraint(:session_occurrences, "session_occurrences_session_template_id_fkey")

    alter table(:session_occurrences) do
      remove :session_template_id
      remove :plan_id
      remove :updated_at
      remove :inserted_at
      remove :notes
      remove :feedback
      remove :completed_at
      remove :started_at
      remove :recommendation_snapshot
      remove :status
      remove :planned_for
    end

    drop constraint(:slot_results, "slot_results_session_occurrence_id_fkey")

    drop constraint(:slot_results, "slot_results_session_slot_id_fkey")

    drop constraint(:slot_results, "slot_results_recommended_item_id_fkey")

    drop constraint(:slot_results, "slot_results_actual_item_id_fkey")

    alter table(:slot_results) do
      modify :actual_item_id, :uuid
      modify :recommended_item_id, :uuid
      modify :session_slot_id, :uuid
      modify :session_occurrence_id, :uuid
    end

    drop table(:session_occurrences)

    drop constraint(:session_slots, "session_slots_plan_id_fkey")

    drop constraint(:session_slots, "session_slots_session_template_id_fkey")

    drop constraint(:session_slots, "session_slots_pool_id_fkey")

    drop_if_exists unique_index(:session_slots, [:session_template_id, :key],
                     name: "session_slots_unique_key_per_template_index"
                   )

    drop table(:session_slots)

    drop constraint(:session_templates, "session_templates_plan_id_fkey")

    drop constraint(:session_templates, "session_templates_environment_id_fkey")

    drop_if_exists unique_index(:session_templates, [:plan_id, :key],
                     name: "session_templates_unique_key_per_plan_index"
                   )

    drop table(:session_templates)

    drop constraint(:slot_results, "slot_results_plan_id_fkey")

    drop table(:slot_results)
  end
end
