defmodule Improve.Repo.Migrations.PreserveSlotPayloads do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:slot_results) do
      add :suggested_payload, :map, null: false, default: %{}
      add :actual_payload, :map, null: false, default: %{}
    end
  end

  def down do
    alter table(:slot_results) do
      remove :actual_payload
      remove :suggested_payload
    end
  end
end
