defmodule Improve.Repo.Migrations.AddTrackGuidanceAndCustomizations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tracks) do
      add :guidance, :map, null: false, default: %{}
    end

    create table(:customizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :kind, :text, null: false, default: "other"
      add :baseline, :map, null: false, default: %{}
      add :recipe, :map, null: false, default: %{}
      add :outputs, :map, null: false, default: %{}
      add :applied_changes, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "customizations_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:customizations, [:plan_id, :key],
             name: "customizations_unique_key_per_plan_index"
           )
  end

  def down do
    drop constraint(:customizations, "customizations_plan_id_fkey")

    drop_if_exists unique_index(:customizations, [:plan_id, :key],
                     name: "customizations_unique_key_per_plan_index"
                   )

    drop table(:customizations)

    alter table(:tracks) do
      remove :guidance
    end
  end
end
