defmodule Improve.Repo.Migrations.AddPlanTimeOffWindows do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:time_off_windows, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :kind, :text, null: false, default: "other"
      add :reason, :text
      add :starts_on, :date, null: false
      add :ends_on, :date, null: false
      add :availability, :text, null: false, default: "fully_off"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :plan_id,
          references(:plans,
            column: :id,
            name: "time_off_windows_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:time_off_windows, [:plan_id, :key],
             name: "time_off_windows_unique_key_per_plan_index"
           )
  end

  def down do
    drop constraint(:time_off_windows, "time_off_windows_plan_id_fkey")

    drop_if_exists unique_index(:time_off_windows, [:plan_id, :key],
                     name: "time_off_windows_unique_key_per_plan_index"
                   )

    drop table(:time_off_windows)
  end
end
